# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:/Users/Joel/Documents/AnalysisGui/ui/abr.ui'
#
# Created: Fri Jan 22 11:12:00 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_abr(object):
    def setupUi(self, Form_abr):
        Form_abr.setObjectName(_fromUtf8("Form_abr"))
        Form_abr.setEnabled(True)
        Form_abr.resize(680, 535)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("horsey.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_abr.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Form_abr)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_comments = QtGui.QLabel(self.centralwidget)
        self.label_comments.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_comments.setFont(font)
        self.label_comments.setObjectName(_fromUtf8("label_comments"))
        self.gridLayout_4.addWidget(self.label_comments, 0, 3, 1, 1)
        self.label_test_num = QtGui.QLabel(self.centralwidget)
        self.label_test_num.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_test_num.setFont(font)
        self.label_test_num.setObjectName(_fromUtf8("label_test_num"))
        self.gridLayout_4.addWidget(self.label_test_num, 0, 0, 1, 1)
        self.comboBox_test_num = QtGui.QComboBox(self.centralwidget)
        self.comboBox_test_num.setEnabled(False)
        self.comboBox_test_num.setObjectName(_fromUtf8("comboBox_test_num"))
        self.gridLayout_4.addWidget(self.comboBox_test_num, 1, 0, 1, 1)
        self.lineEdit_comments = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_comments.setEnabled(False)
        self.lineEdit_comments.setReadOnly(True)
        self.lineEdit_comments.setObjectName(_fromUtf8("lineEdit_comments"))
        self.gridLayout_4.addWidget(self.lineEdit_comments, 1, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_min_sep = QtGui.QLabel(self.centralwidget)
        self.label_min_sep.setEnabled(False)
        self.label_min_sep.setObjectName(_fromUtf8("label_min_sep"))
        self.gridLayout_5.addWidget(self.label_min_sep, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 3, 2, 1)
        self.label_frequency = QtGui.QLabel(self.centralwidget)
        self.label_frequency.setEnabled(False)
        self.label_frequency.setObjectName(_fromUtf8("label_frequency"))
        self.gridLayout_5.addWidget(self.label_frequency, 0, 0, 1, 1)
        self.comboBox_frequency = QtGui.QComboBox(self.centralwidget)
        self.comboBox_frequency.setEnabled(False)
        self.comboBox_frequency.setObjectName(_fromUtf8("comboBox_frequency"))
        self.gridLayout_5.addWidget(self.comboBox_frequency, 1, 0, 1, 1)
        self.doubleSpinBox_min_sep = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_min_sep.setEnabled(False)
        self.doubleSpinBox_min_sep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_min_sep.setDecimals(4)
        self.doubleSpinBox_min_sep.setSingleStep(0.0001)
        self.doubleSpinBox_min_sep.setObjectName(_fromUtf8("doubleSpinBox_min_sep"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_min_sep, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 10, -1, 10)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.view = TraceWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view.sizePolicy().hasHeightForWidth())
        self.view.setSizePolicy(sizePolicy)
        self.view.setObjectName(_fromUtf8("view"))
        self.gridLayout_2.addWidget(self.view, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_title = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.horizontalLayout.addWidget(self.label_title)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.checkBox_custom_window = QtGui.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_custom_window.setFont(font)
        self.checkBox_custom_window.setObjectName(_fromUtf8("checkBox_custom_window"))
        self.verticalLayout_5.addWidget(self.checkBox_custom_window)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_xmax = QtGui.QLabel(self.centralwidget)
        self.label_xmax.setEnabled(False)
        self.label_xmax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_xmax.setObjectName(_fromUtf8("label_xmax"))
        self.verticalLayout_7.addWidget(self.label_xmax)
        self.doubleSpinBox_xmax = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_xmax.setEnabled(False)
        self.doubleSpinBox_xmax.setDecimals(4)
        self.doubleSpinBox_xmax.setMinimum(-1.0)
        self.doubleSpinBox_xmax.setMaximum(100.0)
        self.doubleSpinBox_xmax.setSingleStep(0.001)
        self.doubleSpinBox_xmax.setProperty("value", 0.2)
        self.doubleSpinBox_xmax.setObjectName(_fromUtf8("doubleSpinBox_xmax"))
        self.verticalLayout_7.addWidget(self.doubleSpinBox_xmax)
        self.doubleSpinBox_xmin = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_xmin.setEnabled(False)
        self.doubleSpinBox_xmin.setDecimals(4)
        self.doubleSpinBox_xmin.setMinimum(-1.0)
        self.doubleSpinBox_xmin.setMaximum(100.0)
        self.doubleSpinBox_xmin.setSingleStep(0.001)
        self.doubleSpinBox_xmin.setProperty("value", 0.0)
        self.doubleSpinBox_xmin.setObjectName(_fromUtf8("doubleSpinBox_xmin"))
        self.verticalLayout_7.addWidget(self.doubleSpinBox_xmin)
        self.label_xmin = QtGui.QLabel(self.centralwidget)
        self.label_xmin.setEnabled(False)
        self.label_xmin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_xmin.setObjectName(_fromUtf8("label_xmin"))
        self.verticalLayout_7.addWidget(self.label_xmin)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_ymax = QtGui.QLabel(self.centralwidget)
        self.label_ymax.setEnabled(False)
        self.label_ymax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ymax.setObjectName(_fromUtf8("label_ymax"))
        self.verticalLayout_6.addWidget(self.label_ymax)
        self.doubleSpinBox_ymax = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_ymax.setEnabled(False)
        self.doubleSpinBox_ymax.setDecimals(4)
        self.doubleSpinBox_ymax.setMinimum(-100.0)
        self.doubleSpinBox_ymax.setMaximum(100.0)
        self.doubleSpinBox_ymax.setSingleStep(0.001)
        self.doubleSpinBox_ymax.setProperty("value", 0.1)
        self.doubleSpinBox_ymax.setObjectName(_fromUtf8("doubleSpinBox_ymax"))
        self.verticalLayout_6.addWidget(self.doubleSpinBox_ymax)
        self.doubleSpinBox_ymin = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_ymin.setEnabled(False)
        self.doubleSpinBox_ymin.setDecimals(4)
        self.doubleSpinBox_ymin.setMinimum(-100.0)
        self.doubleSpinBox_ymin.setMaximum(100.0)
        self.doubleSpinBox_ymin.setSingleStep(0.001)
        self.doubleSpinBox_ymin.setProperty("value", -0.1)
        self.doubleSpinBox_ymin.setObjectName(_fromUtf8("doubleSpinBox_ymin"))
        self.verticalLayout_6.addWidget(self.doubleSpinBox_ymin)
        self.label_ymin = QtGui.QLabel(self.centralwidget)
        self.label_ymin.setEnabled(False)
        self.label_ymin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ymin.setObjectName(_fromUtf8("label_ymin"))
        self.verticalLayout_6.addWidget(self.label_ymin)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_2.addWidget(self.line_5)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem5 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        Form_abr.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Form_abr)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Form_abr.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Form_abr)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Form_abr.setStatusBar(self.statusbar)

        self.retranslateUi(Form_abr)
        QtCore.QObject.connect(self.checkBox_custom_window, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_xmax.setEnabled)
        QtCore.QObject.connect(self.checkBox_custom_window, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_xmax.setEnabled)
        QtCore.QObject.connect(self.checkBox_custom_window, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_xmin.setEnabled)
        QtCore.QObject.connect(self.checkBox_custom_window, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_xmin.setEnabled)
        QtCore.QObject.connect(self.checkBox_custom_window, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_ymax.setEnabled)
        QtCore.QObject.connect(self.checkBox_custom_window, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_ymax.setEnabled)
        QtCore.QObject.connect(self.checkBox_custom_window, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_ymin.setEnabled)
        QtCore.QObject.connect(self.checkBox_custom_window, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_ymin.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form_abr)

    def retranslateUi(self, Form_abr):
        Form_abr.setWindowTitle(_translate("Form_abr", "Sparkle Analysis", None))
        self.label_comments.setText(_translate("Form_abr", "Comments:", None))
        self.label_test_num.setText(_translate("Form_abr", "Test Number:", None))
        self.label_min_sep.setText(_translate("Form_abr", "Min Separation:", None))
        self.label_frequency.setText(_translate("Form_abr", "Frequency (hz):", None))
        self.doubleSpinBox_min_sep.setSuffix(_translate("Form_abr", " V", None))
        self.label_title.setText(_translate("Form_abr", "Test Name", None))
        self.checkBox_custom_window.setText(_translate("Form_abr", "Use Custom Window", None))
        self.label_xmax.setText(_translate("Form_abr", "X Max", None))
        self.doubleSpinBox_xmax.setSuffix(_translate("Form_abr", " s", None))
        self.doubleSpinBox_xmin.setSuffix(_translate("Form_abr", " s", None))
        self.label_xmin.setText(_translate("Form_abr", "X Min", None))
        self.label_ymax.setText(_translate("Form_abr", "Y Max", None))
        self.doubleSpinBox_ymax.setSuffix(_translate("Form_abr", " V", None))
        self.doubleSpinBox_ymin.setSuffix(_translate("Form_abr", " V", None))
        self.label_ymin.setText(_translate("Form_abr", "Y Min", None))

from pyqtgraph_widgets import TraceWidget
