# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:/Users/Joel/Documents/AnalysisGui/ui/main2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(797, 698)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_top = QtGui.QGridLayout()
        self.gridLayout_top.setObjectName(_fromUtf8("gridLayout_top"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_top.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_filepath = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_filepath.setObjectName(_fromUtf8("lineEdit_filepath"))
        self.gridLayout_top.addWidget(self.lineEdit_filepath, 1, 0, 1, 1)
        self.pushButton_browse = QtGui.QPushButton(self.centralwidget)
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.gridLayout_top.addWidget(self.pushButton_browse, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_top, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.review = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.review.sizePolicy().hasHeightForWidth())
        self.review.setSizePolicy(sizePolicy)
        self.review.setObjectName(_fromUtf8("review"))
        self.gridLayout_3 = QtGui.QGridLayout(self.review)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_review_comments = QtGui.QGroupBox(self.review)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_review_comments.sizePolicy().hasHeightForWidth())
        self.groupBox_review_comments.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_review_comments.setFont(font)
        self.groupBox_review_comments.setFlat(True)
        self.groupBox_review_comments.setObjectName(_fromUtf8("groupBox_review_comments"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_review_comments)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.lineEdit_review_comments = QtGui.QLineEdit(self.groupBox_review_comments)
        self.lineEdit_review_comments.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_review_comments.sizePolicy().hasHeightForWidth())
        self.lineEdit_review_comments.setSizePolicy(sizePolicy)
        self.lineEdit_review_comments.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_review_comments.setFont(font)
        self.lineEdit_review_comments.setReadOnly(True)
        self.lineEdit_review_comments.setObjectName(_fromUtf8("lineEdit_review_comments"))
        self.gridLayout_13.addWidget(self.lineEdit_review_comments, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_review_comments, 0, 2, 1, 2)
        self.groupBox_review_test = QtGui.QGroupBox(self.review)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_review_test.sizePolicy().hasHeightForWidth())
        self.groupBox_review_test.setSizePolicy(sizePolicy)
        self.groupBox_review_test.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_review_test.setFont(font)
        self.groupBox_review_test.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_review_test.setFlat(True)
        self.groupBox_review_test.setObjectName(_fromUtf8("groupBox_review_test"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_review_test)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.comboBox_review_test_num = QtGui.QComboBox(self.groupBox_review_test)
        self.comboBox_review_test_num.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_review_test_num.sizePolicy().hasHeightForWidth())
        self.comboBox_review_test_num.setSizePolicy(sizePolicy)
        self.comboBox_review_test_num.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_review_test_num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_review_test_num.setFont(font)
        self.comboBox_review_test_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_review_test_num.setObjectName(_fromUtf8("comboBox_review_test_num"))
        self.gridLayout_5.addWidget(self.comboBox_review_test_num, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_review_test, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(34, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.horizontalLayout_review = QtGui.QHBoxLayout()
        self.horizontalLayout_review.setObjectName(_fromUtf8("horizontalLayout_review"))
        self.groupBox_review_trace = QtGui.QGroupBox(self.review)
        self.groupBox_review_trace.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_review_trace.setFont(font)
        self.groupBox_review_trace.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_review_trace.setFlat(True)
        self.groupBox_review_trace.setObjectName(_fromUtf8("groupBox_review_trace"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_review_trace)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.comboBox_review_trace = QtGui.QComboBox(self.groupBox_review_trace)
        self.comboBox_review_trace.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_review_trace.sizePolicy().hasHeightForWidth())
        self.comboBox_review_trace.setSizePolicy(sizePolicy)
        self.comboBox_review_trace.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_review_trace.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_review_trace.setFont(font)
        self.comboBox_review_trace.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_review_trace.setObjectName(_fromUtf8("comboBox_review_trace"))
        self.gridLayout_6.addWidget(self.comboBox_review_trace, 0, 0, 1, 1)
        self.horizontalLayout_review.addWidget(self.groupBox_review_trace)
        self.groupBox_review_rep = QtGui.QGroupBox(self.review)
        self.groupBox_review_rep.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_review_rep.setFont(font)
        self.groupBox_review_rep.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_review_rep.setFlat(True)
        self.groupBox_review_rep.setObjectName(_fromUtf8("groupBox_review_rep"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_review_rep)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.comboBox_review_rep = QtGui.QComboBox(self.groupBox_review_rep)
        self.comboBox_review_rep.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_review_rep.sizePolicy().hasHeightForWidth())
        self.comboBox_review_rep.setSizePolicy(sizePolicy)
        self.comboBox_review_rep.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_review_rep.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_review_rep.setFont(font)
        self.comboBox_review_rep.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_review_rep.setObjectName(_fromUtf8("comboBox_review_rep"))
        self.gridLayout_7.addWidget(self.comboBox_review_rep, 0, 0, 1, 1)
        self.horizontalLayout_review.addWidget(self.groupBox_review_rep)
        self.groupBox_review_channel = QtGui.QGroupBox(self.review)
        self.groupBox_review_channel.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_review_channel.setFont(font)
        self.groupBox_review_channel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_review_channel.setFlat(True)
        self.groupBox_review_channel.setObjectName(_fromUtf8("groupBox_review_channel"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_review_channel)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.comboBox_review_channel = QtGui.QComboBox(self.groupBox_review_channel)
        self.comboBox_review_channel.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_review_channel.sizePolicy().hasHeightForWidth())
        self.comboBox_review_channel.setSizePolicy(sizePolicy)
        self.comboBox_review_channel.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_review_channel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_review_channel.setFont(font)
        self.comboBox_review_channel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_review_channel.setObjectName(_fromUtf8("comboBox_review_channel"))
        self.gridLayout_8.addWidget(self.comboBox_review_channel, 0, 0, 1, 1)
        self.horizontalLayout_review.addWidget(self.groupBox_review_channel)
        self.gridLayout_3.addLayout(self.horizontalLayout_review, 2, 0, 1, 4)
        self.tabWidget.addTab(self.review, _fromUtf8(""))
        self.raster = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raster.sizePolicy().hasHeightForWidth())
        self.raster.setSizePolicy(sizePolicy)
        self.raster.setObjectName(_fromUtf8("raster"))
        self.gridLayout_19 = QtGui.QGridLayout(self.raster)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.groupBox_raster_test = QtGui.QGroupBox(self.raster)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_raster_test.sizePolicy().hasHeightForWidth())
        self.groupBox_raster_test.setSizePolicy(sizePolicy)
        self.groupBox_raster_test.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_raster_test.setFont(font)
        self.groupBox_raster_test.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_raster_test.setFlat(True)
        self.groupBox_raster_test.setObjectName(_fromUtf8("groupBox_raster_test"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_raster_test)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.comboBox_raster_test_num = QtGui.QComboBox(self.groupBox_raster_test)
        self.comboBox_raster_test_num.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_raster_test_num.sizePolicy().hasHeightForWidth())
        self.comboBox_raster_test_num.setSizePolicy(sizePolicy)
        self.comboBox_raster_test_num.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_raster_test_num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_raster_test_num.setFont(font)
        self.comboBox_raster_test_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_raster_test_num.setObjectName(_fromUtf8("comboBox_raster_test_num"))
        self.gridLayout_14.addWidget(self.comboBox_raster_test_num, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_raster_test, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(34, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem1, 0, 1, 1, 1)
        self.groupBox_raster_comments = QtGui.QGroupBox(self.raster)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_raster_comments.sizePolicy().hasHeightForWidth())
        self.groupBox_raster_comments.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_raster_comments.setFont(font)
        self.groupBox_raster_comments.setFlat(True)
        self.groupBox_raster_comments.setObjectName(_fromUtf8("groupBox_raster_comments"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox_raster_comments)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.lineEdit_raster_comments = QtGui.QLineEdit(self.groupBox_raster_comments)
        self.lineEdit_raster_comments.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_raster_comments.sizePolicy().hasHeightForWidth())
        self.lineEdit_raster_comments.setSizePolicy(sizePolicy)
        self.lineEdit_raster_comments.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_raster_comments.setFont(font)
        self.lineEdit_raster_comments.setReadOnly(True)
        self.lineEdit_raster_comments.setObjectName(_fromUtf8("lineEdit_raster_comments"))
        self.gridLayout_18.addWidget(self.lineEdit_raster_comments, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_raster_comments, 0, 2, 1, 1)
        self.horizontalLayout_raster = QtGui.QHBoxLayout()
        self.horizontalLayout_raster.setObjectName(_fromUtf8("horizontalLayout_raster"))
        self.groupBox_raster_trace = QtGui.QGroupBox(self.raster)
        self.groupBox_raster_trace.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_raster_trace.setFont(font)
        self.groupBox_raster_trace.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_raster_trace.setFlat(True)
        self.groupBox_raster_trace.setObjectName(_fromUtf8("groupBox_raster_trace"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_raster_trace)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.comboBox_raster_trace = QtGui.QComboBox(self.groupBox_raster_trace)
        self.comboBox_raster_trace.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_raster_trace.sizePolicy().hasHeightForWidth())
        self.comboBox_raster_trace.setSizePolicy(sizePolicy)
        self.comboBox_raster_trace.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_raster_trace.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_raster_trace.setFont(font)
        self.comboBox_raster_trace.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_raster_trace.setObjectName(_fromUtf8("comboBox_raster_trace"))
        self.gridLayout_15.addWidget(self.comboBox_raster_trace, 0, 0, 1, 1)
        self.horizontalLayout_raster.addWidget(self.groupBox_raster_trace)
        self.groupBox_raster_channel = QtGui.QGroupBox(self.raster)
        self.groupBox_raster_channel.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_raster_channel.setFont(font)
        self.groupBox_raster_channel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_raster_channel.setFlat(True)
        self.groupBox_raster_channel.setObjectName(_fromUtf8("groupBox_raster_channel"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_raster_channel)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.comboBox_raster_channel = QtGui.QComboBox(self.groupBox_raster_channel)
        self.comboBox_raster_channel.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_raster_channel.sizePolicy().hasHeightForWidth())
        self.comboBox_raster_channel.setSizePolicy(sizePolicy)
        self.comboBox_raster_channel.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_raster_channel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_raster_channel.setFont(font)
        self.comboBox_raster_channel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_raster_channel.setObjectName(_fromUtf8("comboBox_raster_channel"))
        self.gridLayout_17.addWidget(self.comboBox_raster_channel, 0, 0, 1, 1)
        self.horizontalLayout_raster.addWidget(self.groupBox_raster_channel)
        self.gridLayout_19.addLayout(self.horizontalLayout_raster, 1, 0, 1, 3)
        self.tabWidget.addTab(self.raster, _fromUtf8(""))
        self.histogram = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram.sizePolicy().hasHeightForWidth())
        self.histogram.setSizePolicy(sizePolicy)
        self.histogram.setObjectName(_fromUtf8("histogram"))
        self.gridLayout_25 = QtGui.QGridLayout(self.histogram)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.groupBox_histogram_test = QtGui.QGroupBox(self.histogram)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_histogram_test.sizePolicy().hasHeightForWidth())
        self.groupBox_histogram_test.setSizePolicy(sizePolicy)
        self.groupBox_histogram_test.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_histogram_test.setFont(font)
        self.groupBox_histogram_test.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_histogram_test.setFlat(True)
        self.groupBox_histogram_test.setObjectName(_fromUtf8("groupBox_histogram_test"))
        self.gridLayout_21 = QtGui.QGridLayout(self.groupBox_histogram_test)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.comboBox_histogram_test_num = QtGui.QComboBox(self.groupBox_histogram_test)
        self.comboBox_histogram_test_num.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_histogram_test_num.sizePolicy().hasHeightForWidth())
        self.comboBox_histogram_test_num.setSizePolicy(sizePolicy)
        self.comboBox_histogram_test_num.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_histogram_test_num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_histogram_test_num.setFont(font)
        self.comboBox_histogram_test_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_histogram_test_num.setObjectName(_fromUtf8("comboBox_histogram_test_num"))
        self.gridLayout_21.addWidget(self.comboBox_histogram_test_num, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_histogram_test, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(34, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem2, 0, 1, 1, 1)
        self.groupBox_histogram_comments = QtGui.QGroupBox(self.histogram)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_histogram_comments.sizePolicy().hasHeightForWidth())
        self.groupBox_histogram_comments.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_histogram_comments.setFont(font)
        self.groupBox_histogram_comments.setFlat(True)
        self.groupBox_histogram_comments.setObjectName(_fromUtf8("groupBox_histogram_comments"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_histogram_comments)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.lineEdit_histogram_comments = QtGui.QLineEdit(self.groupBox_histogram_comments)
        self.lineEdit_histogram_comments.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_histogram_comments.sizePolicy().hasHeightForWidth())
        self.lineEdit_histogram_comments.setSizePolicy(sizePolicy)
        self.lineEdit_histogram_comments.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_histogram_comments.setFont(font)
        self.lineEdit_histogram_comments.setReadOnly(True)
        self.lineEdit_histogram_comments.setObjectName(_fromUtf8("lineEdit_histogram_comments"))
        self.gridLayout_20.addWidget(self.lineEdit_histogram_comments, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_histogram_comments, 0, 2, 1, 1)
        self.horizontalLayout_raster_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_raster_2.setObjectName(_fromUtf8("horizontalLayout_raster_2"))
        self.groupBox_histogram_trace = QtGui.QGroupBox(self.histogram)
        self.groupBox_histogram_trace.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_histogram_trace.setFont(font)
        self.groupBox_histogram_trace.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_histogram_trace.setFlat(True)
        self.groupBox_histogram_trace.setObjectName(_fromUtf8("groupBox_histogram_trace"))
        self.gridLayout_22 = QtGui.QGridLayout(self.groupBox_histogram_trace)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.comboBox_histogram_trace = QtGui.QComboBox(self.groupBox_histogram_trace)
        self.comboBox_histogram_trace.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_histogram_trace.sizePolicy().hasHeightForWidth())
        self.comboBox_histogram_trace.setSizePolicy(sizePolicy)
        self.comboBox_histogram_trace.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_histogram_trace.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_histogram_trace.setFont(font)
        self.comboBox_histogram_trace.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_histogram_trace.setObjectName(_fromUtf8("comboBox_histogram_trace"))
        self.gridLayout_22.addWidget(self.comboBox_histogram_trace, 0, 0, 1, 1)
        self.horizontalLayout_raster_2.addWidget(self.groupBox_histogram_trace)
        self.groupBox_histogram_channel = QtGui.QGroupBox(self.histogram)
        self.groupBox_histogram_channel.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_histogram_channel.setFont(font)
        self.groupBox_histogram_channel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_histogram_channel.setFlat(True)
        self.groupBox_histogram_channel.setObjectName(_fromUtf8("groupBox_histogram_channel"))
        self.gridLayout_24 = QtGui.QGridLayout(self.groupBox_histogram_channel)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.comboBox_histogram_channel = QtGui.QComboBox(self.groupBox_histogram_channel)
        self.comboBox_histogram_channel.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_histogram_channel.sizePolicy().hasHeightForWidth())
        self.comboBox_histogram_channel.setSizePolicy(sizePolicy)
        self.comboBox_histogram_channel.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_histogram_channel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_histogram_channel.setFont(font)
        self.comboBox_histogram_channel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_histogram_channel.setObjectName(_fromUtf8("comboBox_histogram_channel"))
        self.gridLayout_24.addWidget(self.comboBox_histogram_channel, 0, 0, 1, 1)
        self.horizontalLayout_raster_2.addWidget(self.groupBox_histogram_channel)
        self.gridLayout_25.addLayout(self.horizontalLayout_raster_2, 1, 0, 1, 3)
        self.tabWidget.addTab(self.histogram, _fromUtf8(""))
        self.tuning_curve = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tuning_curve.sizePolicy().hasHeightForWidth())
        self.tuning_curve.setSizePolicy(sizePolicy)
        self.tuning_curve.setObjectName(_fromUtf8("tuning_curve"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tuning_curve)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.groupBox_tc_test = QtGui.QGroupBox(self.tuning_curve)
        self.groupBox_tc_test.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_tc_test.setFont(font)
        self.groupBox_tc_test.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_tc_test.setFlat(True)
        self.groupBox_tc_test.setObjectName(_fromUtf8("groupBox_tc_test"))
        self.gridLayout_36 = QtGui.QGridLayout(self.groupBox_tc_test)
        self.gridLayout_36.setObjectName(_fromUtf8("gridLayout_36"))
        self.comboBox_tc_test_num = QtGui.QComboBox(self.groupBox_tc_test)
        self.comboBox_tc_test_num.setEnabled(False)
        self.comboBox_tc_test_num.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_tc_test_num.setMaximumSize(QtCore.QSize(77, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_tc_test_num.setFont(font)
        self.comboBox_tc_test_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_tc_test_num.setObjectName(_fromUtf8("comboBox_tc_test_num"))
        self.gridLayout_36.addWidget(self.comboBox_tc_test_num, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_16.addWidget(self.groupBox_tc_test, 0, 0, 1, 1)
        self.groupBox_tc_channel = QtGui.QGroupBox(self.tuning_curve)
        self.groupBox_tc_channel.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_tc_channel.setFont(font)
        self.groupBox_tc_channel.setFlat(True)
        self.groupBox_tc_channel.setObjectName(_fromUtf8("groupBox_tc_channel"))
        self.gridLayout_37 = QtGui.QGridLayout(self.groupBox_tc_channel)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.comboBox_tc_channel = QtGui.QComboBox(self.groupBox_tc_channel)
        self.comboBox_tc_channel.setEnabled(False)
        self.comboBox_tc_channel.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_tc_channel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_tc_channel.setFont(font)
        self.comboBox_tc_channel.setObjectName(_fromUtf8("comboBox_tc_channel"))
        self.gridLayout_37.addWidget(self.comboBox_tc_channel, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_16.addWidget(self.groupBox_tc_channel, 0, 1, 1, 1)
        self.groupBox_tc_comments = QtGui.QGroupBox(self.tuning_curve)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_tc_comments.setFont(font)
        self.groupBox_tc_comments.setFlat(True)
        self.groupBox_tc_comments.setObjectName(_fromUtf8("groupBox_tc_comments"))
        self.gridLayout_23 = QtGui.QGridLayout(self.groupBox_tc_comments)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.lineEdit_tc_comments = QtGui.QLineEdit(self.groupBox_tc_comments)
        self.lineEdit_tc_comments.setEnabled(False)
        self.lineEdit_tc_comments.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_tc_comments.setFont(font)
        self.lineEdit_tc_comments.setReadOnly(True)
        self.lineEdit_tc_comments.setObjectName(_fromUtf8("lineEdit_tc_comments"))
        self.gridLayout_23.addWidget(self.lineEdit_tc_comments, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_tc_comments, 0, 2, 1, 1)
        self.gridLayout_39 = QtGui.QGridLayout()
        self.gridLayout_39.setObjectName(_fromUtf8("gridLayout_39"))
        self.groupBox_tc_plot = QtGui.QGroupBox(self.tuning_curve)
        self.groupBox_tc_plot.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_tc_plot.sizePolicy().hasHeightForWidth())
        self.groupBox_tc_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_tc_plot.setFont(font)
        self.groupBox_tc_plot.setFlat(True)
        self.groupBox_tc_plot.setObjectName(_fromUtf8("groupBox_tc_plot"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_tc_plot)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.radioButton_tc_freq = QtGui.QRadioButton(self.groupBox_tc_plot)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_tc_freq.setFont(font)
        self.radioButton_tc_freq.setChecked(True)
        self.radioButton_tc_freq.setObjectName(_fromUtf8("radioButton_tc_freq"))
        self.horizontalLayout_7.addWidget(self.radioButton_tc_freq)
        self.radioButton_tc_contour = QtGui.QRadioButton(self.groupBox_tc_plot)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_tc_contour.setFont(font)
        self.radioButton_tc_contour.setObjectName(_fromUtf8("radioButton_tc_contour"))
        self.horizontalLayout_7.addWidget(self.radioButton_tc_contour)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.gridLayout_39.addWidget(self.groupBox_tc_plot, 0, 1, 1, 1)
        self.groupBox_tc_error = QtGui.QGroupBox(self.tuning_curve)
        self.groupBox_tc_error.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_tc_error.setFont(font)
        self.groupBox_tc_error.setFlat(True)
        self.groupBox_tc_error.setObjectName(_fromUtf8("groupBox_tc_error"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_tc_error)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.radioButton_tc_stddeviation = QtGui.QRadioButton(self.groupBox_tc_error)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_tc_stddeviation.setFont(font)
        self.radioButton_tc_stddeviation.setChecked(True)
        self.radioButton_tc_stddeviation.setObjectName(_fromUtf8("radioButton_tc_stddeviation"))
        self.horizontalLayout_6.addWidget(self.radioButton_tc_stddeviation)
        self.radioButton_tc_stderror = QtGui.QRadioButton(self.groupBox_tc_error)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_tc_stderror.setFont(font)
        self.radioButton_tc_stderror.setObjectName(_fromUtf8("radioButton_tc_stderror"))
        self.horizontalLayout_6.addWidget(self.radioButton_tc_stderror)
        self.radioButton_tc_none = QtGui.QRadioButton(self.groupBox_tc_error)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_tc_none.setFont(font)
        self.radioButton_tc_none.setObjectName(_fromUtf8("radioButton_tc_none"))
        self.horizontalLayout_6.addWidget(self.radioButton_tc_none)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.gridLayout_39.addWidget(self.groupBox_tc_error, 2, 1, 1, 1)
        self.groupBox_tc_units = QtGui.QGroupBox(self.tuning_curve)
        self.groupBox_tc_units.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_tc_units.setFont(font)
        self.groupBox_tc_units.setFlat(True)
        self.groupBox_tc_units.setObjectName(_fromUtf8("groupBox_tc_units"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_tc_units)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.radioButton_tc_meanspikes = QtGui.QRadioButton(self.groupBox_tc_units)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_tc_meanspikes.setFont(font)
        self.radioButton_tc_meanspikes.setChecked(True)
        self.radioButton_tc_meanspikes.setObjectName(_fromUtf8("radioButton_tc_meanspikes"))
        self.horizontalLayout_5.addWidget(self.radioButton_tc_meanspikes)
        self.radioButton_tc_responserate = QtGui.QRadioButton(self.groupBox_tc_units)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_tc_responserate.setFont(font)
        self.radioButton_tc_responserate.setObjectName(_fromUtf8("radioButton_tc_responserate"))
        self.horizontalLayout_5.addWidget(self.radioButton_tc_responserate)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout_39.addWidget(self.groupBox_tc_units, 1, 1, 1, 1)
        self.groupBox_tc_viewcontrols = QtGui.QGroupBox(self.tuning_curve)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_tc_viewcontrols.sizePolicy().hasHeightForWidth())
        self.groupBox_tc_viewcontrols.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_tc_viewcontrols.setFont(font)
        self.groupBox_tc_viewcontrols.setObjectName(_fromUtf8("groupBox_tc_viewcontrols"))
        self.gridLayout_41 = QtGui.QGridLayout(self.groupBox_tc_viewcontrols)
        self.gridLayout_41.setObjectName(_fromUtf8("gridLayout_41"))
        self.gridLayout_52 = QtGui.QGridLayout()
        self.gridLayout_52.setObjectName(_fromUtf8("gridLayout_52"))
        self.groupBox_tc_view_trace = QtGui.QGroupBox(self.groupBox_tc_viewcontrols)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_tc_view_trace.setFont(font)
        self.groupBox_tc_view_trace.setFlat(True)
        self.groupBox_tc_view_trace.setObjectName(_fromUtf8("groupBox_tc_view_trace"))
        self.gridLayout_53 = QtGui.QGridLayout(self.groupBox_tc_view_trace)
        self.gridLayout_53.setObjectName(_fromUtf8("gridLayout_53"))
        self.comboBox_tc_view_trace = QtGui.QComboBox(self.groupBox_tc_view_trace)
        self.comboBox_tc_view_trace.setEnabled(False)
        self.comboBox_tc_view_trace.setObjectName(_fromUtf8("comboBox_tc_view_trace"))
        self.gridLayout_53.addWidget(self.comboBox_tc_view_trace, 0, 0, 1, 1)
        self.gridLayout_52.addWidget(self.groupBox_tc_view_trace, 0, 0, 1, 1)
        self.groupBox_tc_view_channel = QtGui.QGroupBox(self.groupBox_tc_viewcontrols)
        self.groupBox_tc_view_channel.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_tc_view_channel.setFont(font)
        self.groupBox_tc_view_channel.setFlat(True)
        self.groupBox_tc_view_channel.setObjectName(_fromUtf8("groupBox_tc_view_channel"))
        self.gridLayout_54 = QtGui.QGridLayout(self.groupBox_tc_view_channel)
        self.gridLayout_54.setObjectName(_fromUtf8("gridLayout_54"))
        self.comboBox_tc_view_channel = QtGui.QComboBox(self.groupBox_tc_view_channel)
        self.comboBox_tc_view_channel.setEnabled(False)
        self.comboBox_tc_view_channel.setObjectName(_fromUtf8("comboBox_tc_view_channel"))
        self.gridLayout_54.addWidget(self.comboBox_tc_view_channel, 0, 0, 1, 1)
        self.gridLayout_52.addWidget(self.groupBox_tc_view_channel, 2, 0, 1, 1)
        self.groupBox_tc_view_rep = QtGui.QGroupBox(self.groupBox_tc_viewcontrols)
        self.groupBox_tc_view_rep.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_tc_view_rep.setFont(font)
        self.groupBox_tc_view_rep.setFlat(True)
        self.groupBox_tc_view_rep.setObjectName(_fromUtf8("groupBox_tc_view_rep"))
        self.gridLayout_55 = QtGui.QGridLayout(self.groupBox_tc_view_rep)
        self.gridLayout_55.setObjectName(_fromUtf8("gridLayout_55"))
        self.comboBox_tc_view_rep = QtGui.QComboBox(self.groupBox_tc_view_rep)
        self.comboBox_tc_view_rep.setEnabled(False)
        self.comboBox_tc_view_rep.setObjectName(_fromUtf8("comboBox_tc_view_rep"))
        self.gridLayout_55.addWidget(self.comboBox_tc_view_rep, 0, 0, 1, 1)
        self.gridLayout_52.addWidget(self.groupBox_tc_view_rep, 1, 0, 1, 1)
        self.gridLayout_41.addLayout(self.gridLayout_52, 0, 0, 1, 1)
        self.gridLayout_39.addWidget(self.groupBox_tc_viewcontrols, 0, 0, 3, 1)
        self.gridLayout_16.addLayout(self.gridLayout_39, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tuning_curve, _fromUtf8(""))
        self.abr = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abr.sizePolicy().hasHeightForWidth())
        self.abr.setSizePolicy(sizePolicy)
        self.abr.setObjectName(_fromUtf8("abr"))
        self.gridLayout_30 = QtGui.QGridLayout(self.abr)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.groupBox_abr_min_sep = QtGui.QGroupBox(self.abr)
        self.groupBox_abr_min_sep.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_abr_min_sep.setFont(font)
        self.groupBox_abr_min_sep.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_abr_min_sep.setFlat(True)
        self.groupBox_abr_min_sep.setObjectName(_fromUtf8("groupBox_abr_min_sep"))
        self.gridLayout_29 = QtGui.QGridLayout(self.groupBox_abr_min_sep)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.doubleSpinBox_abr_min_sep = QtGui.QDoubleSpinBox(self.groupBox_abr_min_sep)
        self.doubleSpinBox_abr_min_sep.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_abr_min_sep.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_abr_min_sep.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.doubleSpinBox_abr_min_sep.setFont(font)
        self.doubleSpinBox_abr_min_sep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_abr_min_sep.setDecimals(4)
        self.doubleSpinBox_abr_min_sep.setSingleStep(0.0001)
        self.doubleSpinBox_abr_min_sep.setObjectName(_fromUtf8("doubleSpinBox_abr_min_sep"))
        self.gridLayout_29.addWidget(self.doubleSpinBox_abr_min_sep, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_abr_min_sep, 1, 2, 1, 1)
        self.groupBox_abr_test = QtGui.QGroupBox(self.abr)
        self.groupBox_abr_test.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_abr_test.setFont(font)
        self.groupBox_abr_test.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_abr_test.setFlat(True)
        self.groupBox_abr_test.setObjectName(_fromUtf8("groupBox_abr_test"))
        self.gridLayout_26 = QtGui.QGridLayout(self.groupBox_abr_test)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.comboBox_abr_test_num = QtGui.QComboBox(self.groupBox_abr_test)
        self.comboBox_abr_test_num.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_abr_test_num.sizePolicy().hasHeightForWidth())
        self.comboBox_abr_test_num.setSizePolicy(sizePolicy)
        self.comboBox_abr_test_num.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_abr_test_num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_abr_test_num.setFont(font)
        self.comboBox_abr_test_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_abr_test_num.setObjectName(_fromUtf8("comboBox_abr_test_num"))
        self.gridLayout_26.addWidget(self.comboBox_abr_test_num, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_abr_test, 0, 0, 1, 1)
        self.groupBox_abr_frequency = QtGui.QGroupBox(self.abr)
        self.groupBox_abr_frequency.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_abr_frequency.setFont(font)
        self.groupBox_abr_frequency.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_abr_frequency.setFlat(True)
        self.groupBox_abr_frequency.setObjectName(_fromUtf8("groupBox_abr_frequency"))
        self.gridLayout_28 = QtGui.QGridLayout(self.groupBox_abr_frequency)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.comboBox_abr_frequency = QtGui.QComboBox(self.groupBox_abr_frequency)
        self.comboBox_abr_frequency.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_abr_frequency.sizePolicy().hasHeightForWidth())
        self.comboBox_abr_frequency.setSizePolicy(sizePolicy)
        self.comboBox_abr_frequency.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_abr_frequency.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_abr_frequency.setFont(font)
        self.comboBox_abr_frequency.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_abr_frequency.setObjectName(_fromUtf8("comboBox_abr_frequency"))
        self.gridLayout_28.addWidget(self.comboBox_abr_frequency, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_abr_frequency, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem6, 1, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem7, 1, 3, 1, 1)
        self.groupBox_abr_comments = QtGui.QGroupBox(self.abr)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_abr_comments.setFont(font)
        self.groupBox_abr_comments.setFlat(True)
        self.groupBox_abr_comments.setObjectName(_fromUtf8("groupBox_abr_comments"))
        self.gridLayout_27 = QtGui.QGridLayout(self.groupBox_abr_comments)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.lineEdit_abr_comments = QtGui.QLineEdit(self.groupBox_abr_comments)
        self.lineEdit_abr_comments.setEnabled(False)
        self.lineEdit_abr_comments.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_abr_comments.setFont(font)
        self.lineEdit_abr_comments.setReadOnly(True)
        self.lineEdit_abr_comments.setObjectName(_fromUtf8("lineEdit_abr_comments"))
        self.gridLayout_27.addWidget(self.lineEdit_abr_comments, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_abr_comments, 0, 2, 1, 2)
        self.tabWidget.addTab(self.abr, _fromUtf8(""))
        self.io_test = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.io_test.sizePolicy().hasHeightForWidth())
        self.io_test.setSizePolicy(sizePolicy)
        self.io_test.setObjectName(_fromUtf8("io_test"))
        self.gridLayout_48 = QtGui.QGridLayout(self.io_test)
        self.gridLayout_48.setObjectName(_fromUtf8("gridLayout_48"))
        self.groupBox_io_test = QtGui.QGroupBox(self.io_test)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_io_test.sizePolicy().hasHeightForWidth())
        self.groupBox_io_test.setSizePolicy(sizePolicy)
        self.groupBox_io_test.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_io_test.setFont(font)
        self.groupBox_io_test.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_io_test.setFlat(True)
        self.groupBox_io_test.setObjectName(_fromUtf8("groupBox_io_test"))
        self.gridLayout_43 = QtGui.QGridLayout(self.groupBox_io_test)
        self.gridLayout_43.setObjectName(_fromUtf8("gridLayout_43"))
        self.comboBox_io_test_num = QtGui.QComboBox(self.groupBox_io_test)
        self.comboBox_io_test_num.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_io_test_num.sizePolicy().hasHeightForWidth())
        self.comboBox_io_test_num.setSizePolicy(sizePolicy)
        self.comboBox_io_test_num.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_io_test_num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_io_test_num.setFont(font)
        self.comboBox_io_test_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_io_test_num.setObjectName(_fromUtf8("comboBox_io_test_num"))
        self.gridLayout_43.addWidget(self.comboBox_io_test_num, 0, 0, 1, 1)
        self.gridLayout_48.addWidget(self.groupBox_io_test, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(34, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_48.addItem(spacerItem8, 0, 1, 1, 1)
        self.groupBox_io_comments = QtGui.QGroupBox(self.io_test)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_io_comments.sizePolicy().hasHeightForWidth())
        self.groupBox_io_comments.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_io_comments.setFont(font)
        self.groupBox_io_comments.setFlat(True)
        self.groupBox_io_comments.setObjectName(_fromUtf8("groupBox_io_comments"))
        self.gridLayout_44 = QtGui.QGridLayout(self.groupBox_io_comments)
        self.gridLayout_44.setObjectName(_fromUtf8("gridLayout_44"))
        self.lineEdit_io_comments = QtGui.QLineEdit(self.groupBox_io_comments)
        self.lineEdit_io_comments.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_io_comments.sizePolicy().hasHeightForWidth())
        self.lineEdit_io_comments.setSizePolicy(sizePolicy)
        self.lineEdit_io_comments.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_io_comments.setFont(font)
        self.lineEdit_io_comments.setReadOnly(True)
        self.lineEdit_io_comments.setObjectName(_fromUtf8("lineEdit_io_comments"))
        self.gridLayout_44.addWidget(self.lineEdit_io_comments, 0, 0, 1, 1)
        self.gridLayout_48.addWidget(self.groupBox_io_comments, 0, 2, 1, 1)
        self.gridLayout_45 = QtGui.QGridLayout()
        self.gridLayout_45.setObjectName(_fromUtf8("gridLayout_45"))
        self.scrollArea_io = QtGui.QScrollArea(self.io_test)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_io.sizePolicy().hasHeightForWidth())
        self.scrollArea_io.setSizePolicy(sizePolicy)
        self.scrollArea_io.setWidgetResizable(True)
        self.scrollArea_io.setObjectName(_fromUtf8("scrollArea_io"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 557, 92))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.scrollArea_io.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_45.addWidget(self.scrollArea_io, 1, 1, 1, 1)
        self.groupBox_io_error = QtGui.QGroupBox(self.io_test)
        self.groupBox_io_error.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_io_error.setFont(font)
        self.groupBox_io_error.setFlat(True)
        self.groupBox_io_error.setObjectName(_fromUtf8("groupBox_io_error"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_io_error)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.radioButton_io_stddeviation = QtGui.QRadioButton(self.groupBox_io_error)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_io_stddeviation.setFont(font)
        self.radioButton_io_stddeviation.setChecked(True)
        self.radioButton_io_stddeviation.setObjectName(_fromUtf8("radioButton_io_stddeviation"))
        self.horizontalLayout_8.addWidget(self.radioButton_io_stddeviation)
        self.radioButton_io_stderror = QtGui.QRadioButton(self.groupBox_io_error)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_io_stderror.setFont(font)
        self.radioButton_io_stderror.setObjectName(_fromUtf8("radioButton_io_stderror"))
        self.horizontalLayout_8.addWidget(self.radioButton_io_stderror)
        self.radioButton_io_none = QtGui.QRadioButton(self.groupBox_io_error)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_io_none.setFont(font)
        self.radioButton_io_none.setObjectName(_fromUtf8("radioButton_io_none"))
        self.horizontalLayout_8.addWidget(self.radioButton_io_none)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.gridLayout_45.addWidget(self.groupBox_io_error, 2, 1, 1, 1)
        self.groupBox_io_viewcontrols = QtGui.QGroupBox(self.io_test)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_io_viewcontrols.sizePolicy().hasHeightForWidth())
        self.groupBox_io_viewcontrols.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_io_viewcontrols.setFont(font)
        self.groupBox_io_viewcontrols.setObjectName(_fromUtf8("groupBox_io_viewcontrols"))
        self.gridLayout_46 = QtGui.QGridLayout(self.groupBox_io_viewcontrols)
        self.gridLayout_46.setObjectName(_fromUtf8("gridLayout_46"))
        self.gridLayout_47 = QtGui.QGridLayout()
        self.gridLayout_47.setObjectName(_fromUtf8("gridLayout_47"))
        self.groupBox_io_view_trace = QtGui.QGroupBox(self.groupBox_io_viewcontrols)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_io_view_trace.setFont(font)
        self.groupBox_io_view_trace.setFlat(True)
        self.groupBox_io_view_trace.setObjectName(_fromUtf8("groupBox_io_view_trace"))
        self.gridLayout_49 = QtGui.QGridLayout(self.groupBox_io_view_trace)
        self.gridLayout_49.setObjectName(_fromUtf8("gridLayout_49"))
        self.comboBox_io_view_trace = QtGui.QComboBox(self.groupBox_io_view_trace)
        self.comboBox_io_view_trace.setEnabled(False)
        self.comboBox_io_view_trace.setObjectName(_fromUtf8("comboBox_io_view_trace"))
        self.gridLayout_49.addWidget(self.comboBox_io_view_trace, 0, 0, 1, 1)
        self.gridLayout_47.addWidget(self.groupBox_io_view_trace, 0, 0, 1, 1)
        self.groupBox_io_view_channel = QtGui.QGroupBox(self.groupBox_io_viewcontrols)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_io_view_channel.setFont(font)
        self.groupBox_io_view_channel.setFlat(True)
        self.groupBox_io_view_channel.setObjectName(_fromUtf8("groupBox_io_view_channel"))
        self.gridLayout_51 = QtGui.QGridLayout(self.groupBox_io_view_channel)
        self.gridLayout_51.setObjectName(_fromUtf8("gridLayout_51"))
        self.comboBox_io_view_channel = QtGui.QComboBox(self.groupBox_io_view_channel)
        self.comboBox_io_view_channel.setEnabled(False)
        self.comboBox_io_view_channel.setObjectName(_fromUtf8("comboBox_io_view_channel"))
        self.gridLayout_51.addWidget(self.comboBox_io_view_channel, 0, 0, 1, 1)
        self.gridLayout_47.addWidget(self.groupBox_io_view_channel, 2, 0, 1, 1)
        self.groupBox_io_view_rep = QtGui.QGroupBox(self.groupBox_io_viewcontrols)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_io_view_rep.setFont(font)
        self.groupBox_io_view_rep.setFlat(True)
        self.groupBox_io_view_rep.setObjectName(_fromUtf8("groupBox_io_view_rep"))
        self.gridLayout_50 = QtGui.QGridLayout(self.groupBox_io_view_rep)
        self.gridLayout_50.setObjectName(_fromUtf8("gridLayout_50"))
        self.comboBox_io_view_rep = QtGui.QComboBox(self.groupBox_io_view_rep)
        self.comboBox_io_view_rep.setEnabled(False)
        self.comboBox_io_view_rep.setObjectName(_fromUtf8("comboBox_io_view_rep"))
        self.gridLayout_50.addWidget(self.comboBox_io_view_rep, 0, 0, 1, 1)
        self.gridLayout_47.addWidget(self.groupBox_io_view_rep, 1, 0, 1, 1)
        self.gridLayout_46.addLayout(self.gridLayout_47, 0, 0, 2, 1)
        self.gridLayout_45.addWidget(self.groupBox_io_viewcontrols, 0, 0, 3, 1)
        self.gridLayout_48.addLayout(self.gridLayout_45, 1, 0, 1, 3)
        self.tabWidget.addTab(self.io_test, _fromUtf8(""))
        self.spike_rates = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spike_rates.sizePolicy().hasHeightForWidth())
        self.spike_rates.setSizePolicy(sizePolicy)
        self.spike_rates.setObjectName(_fromUtf8("spike_rates"))
        self.gridLayout_42 = QtGui.QGridLayout(self.spike_rates)
        self.gridLayout_42.setObjectName(_fromUtf8("gridLayout_42"))
        self.groupBox_sr_test = QtGui.QGroupBox(self.spike_rates)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_sr_test.sizePolicy().hasHeightForWidth())
        self.groupBox_sr_test.setSizePolicy(sizePolicy)
        self.groupBox_sr_test.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_sr_test.setFont(font)
        self.groupBox_sr_test.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_sr_test.setFlat(True)
        self.groupBox_sr_test.setObjectName(_fromUtf8("groupBox_sr_test"))
        self.gridLayout_56 = QtGui.QGridLayout(self.groupBox_sr_test)
        self.gridLayout_56.setObjectName(_fromUtf8("gridLayout_56"))
        self.comboBox_sr_test_num = QtGui.QComboBox(self.groupBox_sr_test)
        self.comboBox_sr_test_num.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_sr_test_num.sizePolicy().hasHeightForWidth())
        self.comboBox_sr_test_num.setSizePolicy(sizePolicy)
        self.comboBox_sr_test_num.setMinimumSize(QtCore.QSize(75, 20))
        self.comboBox_sr_test_num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_sr_test_num.setFont(font)
        self.comboBox_sr_test_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_sr_test_num.setObjectName(_fromUtf8("comboBox_sr_test_num"))
        self.gridLayout_56.addWidget(self.comboBox_sr_test_num, 0, 0, 1, 1)
        self.gridLayout_42.addWidget(self.groupBox_sr_test, 0, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(34, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_42.addItem(spacerItem10, 0, 1, 1, 1)
        self.groupBox_sr_comments = QtGui.QGroupBox(self.spike_rates)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_sr_comments.sizePolicy().hasHeightForWidth())
        self.groupBox_sr_comments.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_sr_comments.setFont(font)
        self.groupBox_sr_comments.setFlat(True)
        self.groupBox_sr_comments.setObjectName(_fromUtf8("groupBox_sr_comments"))
        self.gridLayout_63 = QtGui.QGridLayout(self.groupBox_sr_comments)
        self.gridLayout_63.setObjectName(_fromUtf8("gridLayout_63"))
        self.lineEdit_sr_comments = QtGui.QLineEdit(self.groupBox_sr_comments)
        self.lineEdit_sr_comments.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_sr_comments.sizePolicy().hasHeightForWidth())
        self.lineEdit_sr_comments.setSizePolicy(sizePolicy)
        self.lineEdit_sr_comments.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_sr_comments.setFont(font)
        self.lineEdit_sr_comments.setReadOnly(True)
        self.lineEdit_sr_comments.setObjectName(_fromUtf8("lineEdit_sr_comments"))
        self.gridLayout_63.addWidget(self.lineEdit_sr_comments, 0, 0, 1, 1)
        self.gridLayout_42.addWidget(self.groupBox_sr_comments, 0, 2, 1, 1)
        self.gridLayout_57 = QtGui.QGridLayout()
        self.gridLayout_57.setObjectName(_fromUtf8("gridLayout_57"))
        self.groupBox_sr_viewcontrols = QtGui.QGroupBox(self.spike_rates)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_sr_viewcontrols.sizePolicy().hasHeightForWidth())
        self.groupBox_sr_viewcontrols.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_sr_viewcontrols.setFont(font)
        self.groupBox_sr_viewcontrols.setObjectName(_fromUtf8("groupBox_sr_viewcontrols"))
        self.gridLayout_58 = QtGui.QGridLayout(self.groupBox_sr_viewcontrols)
        self.gridLayout_58.setObjectName(_fromUtf8("gridLayout_58"))
        self.gridLayout_59 = QtGui.QGridLayout()
        self.gridLayout_59.setObjectName(_fromUtf8("gridLayout_59"))
        self.groupBox_sr_view_trace = QtGui.QGroupBox(self.groupBox_sr_viewcontrols)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_sr_view_trace.setFont(font)
        self.groupBox_sr_view_trace.setFlat(True)
        self.groupBox_sr_view_trace.setObjectName(_fromUtf8("groupBox_sr_view_trace"))
        self.gridLayout_60 = QtGui.QGridLayout(self.groupBox_sr_view_trace)
        self.gridLayout_60.setObjectName(_fromUtf8("gridLayout_60"))
        self.comboBox_sr_view_trace = QtGui.QComboBox(self.groupBox_sr_view_trace)
        self.comboBox_sr_view_trace.setEnabled(False)
        self.comboBox_sr_view_trace.setObjectName(_fromUtf8("comboBox_sr_view_trace"))
        self.gridLayout_60.addWidget(self.comboBox_sr_view_trace, 0, 0, 1, 1)
        self.gridLayout_59.addWidget(self.groupBox_sr_view_trace, 0, 0, 1, 1)
        self.groupBox_sr_view_channel = QtGui.QGroupBox(self.groupBox_sr_viewcontrols)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_sr_view_channel.setFont(font)
        self.groupBox_sr_view_channel.setFlat(True)
        self.groupBox_sr_view_channel.setObjectName(_fromUtf8("groupBox_sr_view_channel"))
        self.gridLayout_61 = QtGui.QGridLayout(self.groupBox_sr_view_channel)
        self.gridLayout_61.setObjectName(_fromUtf8("gridLayout_61"))
        self.comboBox_sr_view_channel = QtGui.QComboBox(self.groupBox_sr_view_channel)
        self.comboBox_sr_view_channel.setEnabled(False)
        self.comboBox_sr_view_channel.setObjectName(_fromUtf8("comboBox_sr_view_channel"))
        self.gridLayout_61.addWidget(self.comboBox_sr_view_channel, 0, 0, 1, 1)
        self.gridLayout_59.addWidget(self.groupBox_sr_view_channel, 2, 0, 1, 1)
        self.groupBox_sr_view_rep = QtGui.QGroupBox(self.groupBox_sr_viewcontrols)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_sr_view_rep.setFont(font)
        self.groupBox_sr_view_rep.setFlat(True)
        self.groupBox_sr_view_rep.setObjectName(_fromUtf8("groupBox_sr_view_rep"))
        self.gridLayout_62 = QtGui.QGridLayout(self.groupBox_sr_view_rep)
        self.gridLayout_62.setObjectName(_fromUtf8("gridLayout_62"))
        self.comboBox_sr_view_rep = QtGui.QComboBox(self.groupBox_sr_view_rep)
        self.comboBox_sr_view_rep.setEnabled(False)
        self.comboBox_sr_view_rep.setObjectName(_fromUtf8("comboBox_sr_view_rep"))
        self.gridLayout_62.addWidget(self.comboBox_sr_view_rep, 0, 0, 1, 1)
        self.gridLayout_59.addWidget(self.groupBox_sr_view_rep, 1, 0, 1, 1)
        self.gridLayout_58.addLayout(self.gridLayout_59, 0, 0, 1, 1)
        self.gridLayout_57.addWidget(self.groupBox_sr_viewcontrols, 0, 0, 2, 1)
        self.scrollArea_sr = QtGui.QScrollArea(self.spike_rates)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_sr.sizePolicy().hasHeightForWidth())
        self.scrollArea_sr.setSizePolicy(sizePolicy)
        self.scrollArea_sr.setWidgetResizable(True)
        self.scrollArea_sr.setObjectName(_fromUtf8("scrollArea_sr"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 557, 154))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.scrollArea_sr.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_57.addWidget(self.scrollArea_sr, 1, 1, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_57, 1, 0, 1, 3)
        self.tabWidget.addTab(self.spike_rates, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_bottom = QtGui.QGridLayout()
        self.gridLayout_bottom.setObjectName(_fromUtf8("gridLayout_bottom"))
        self.pushButtonGenerate = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonGenerate.setFont(font)
        self.pushButtonGenerate.setObjectName(_fromUtf8("pushButtonGenerate"))
        self.gridLayout_bottom.addWidget(self.pushButtonGenerate, 1, 0, 1, 4)
        self.dockWidget_attributes = QtGui.QDockWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_attributes.sizePolicy().hasHeightForWidth())
        self.dockWidget_attributes.setSizePolicy(sizePolicy)
        self.dockWidget_attributes.setObjectName(_fromUtf8("dockWidget_attributes"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.gridLayout_11 = QtGui.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.textEdit_attributes = QtGui.QTextEdit(self.dockWidgetContents_4)
        self.textEdit_attributes.setReadOnly(True)
        self.textEdit_attributes.setObjectName(_fromUtf8("textEdit_attributes"))
        self.gridLayout_11.addWidget(self.textEdit_attributes, 0, 0, 1, 1)
        self.dockWidget_attributes.setWidget(self.dockWidgetContents_4)
        self.gridLayout_bottom.addWidget(self.dockWidget_attributes, 0, 0, 1, 1)
        self.dockWidget_log = QtGui.QDockWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_log.sizePolicy().hasHeightForWidth())
        self.dockWidget_log.setSizePolicy(sizePolicy)
        self.dockWidget_log.setObjectName(_fromUtf8("dockWidget_log"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.textEdit_log = QtGui.QTextEdit(self.dockWidgetContents_3)
        self.textEdit_log.setEnabled(True)
        self.textEdit_log.setReadOnly(True)
        self.textEdit_log.setObjectName(_fromUtf8("textEdit_log"))
        self.gridLayout_9.addWidget(self.textEdit_log, 0, 0, 1, 1)
        self.dockWidget_log.setWidget(self.dockWidgetContents_3)
        self.gridLayout_bottom.addWidget(self.dockWidget_log, 0, 1, 1, 1)
        self.groupBox_window = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_window.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_window.setFont(font)
        self.groupBox_window.setFlat(True)
        self.groupBox_window.setCheckable(True)
        self.groupBox_window.setChecked(False)
        self.groupBox_window.setObjectName(_fromUtf8("groupBox_window"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_window)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_x = QtGui.QVBoxLayout()
        self.verticalLayout_x.setObjectName(_fromUtf8("verticalLayout_x"))
        self.label_xmax = QtGui.QLabel(self.groupBox_window)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_xmax.setFont(font)
        self.label_xmax.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_xmax.setObjectName(_fromUtf8("label_xmax"))
        self.verticalLayout_x.addWidget(self.label_xmax)
        self.doubleSpinBox_xmax = QtGui.QDoubleSpinBox(self.groupBox_window)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.doubleSpinBox_xmax.setFont(font)
        self.doubleSpinBox_xmax.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_xmax.setDecimals(4)
        self.doubleSpinBox_xmax.setMinimum(-100.0)
        self.doubleSpinBox_xmax.setMaximum(100.0)
        self.doubleSpinBox_xmax.setSingleStep(0.001)
        self.doubleSpinBox_xmax.setProperty("value", 0.2)
        self.doubleSpinBox_xmax.setObjectName(_fromUtf8("doubleSpinBox_xmax"))
        self.verticalLayout_x.addWidget(self.doubleSpinBox_xmax)
        self.doubleSpinBox_xmin = QtGui.QDoubleSpinBox(self.groupBox_window)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.doubleSpinBox_xmin.setFont(font)
        self.doubleSpinBox_xmin.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_xmin.setDecimals(4)
        self.doubleSpinBox_xmin.setMinimum(-100.0)
        self.doubleSpinBox_xmin.setMaximum(100.0)
        self.doubleSpinBox_xmin.setSingleStep(0.001)
        self.doubleSpinBox_xmin.setObjectName(_fromUtf8("doubleSpinBox_xmin"))
        self.verticalLayout_x.addWidget(self.doubleSpinBox_xmin)
        self.label_xmin = QtGui.QLabel(self.groupBox_window)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_xmin.setFont(font)
        self.label_xmin.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_xmin.setObjectName(_fromUtf8("label_xmin"))
        self.verticalLayout_x.addWidget(self.label_xmin)
        self.horizontalLayout.addLayout(self.verticalLayout_x)
        self.verticalLayout_y = QtGui.QVBoxLayout()
        self.verticalLayout_y.setObjectName(_fromUtf8("verticalLayout_y"))
        self.label_ymax = QtGui.QLabel(self.groupBox_window)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ymax.setFont(font)
        self.label_ymax.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_ymax.setObjectName(_fromUtf8("label_ymax"))
        self.verticalLayout_y.addWidget(self.label_ymax)
        self.doubleSpinBox_ymax = QtGui.QDoubleSpinBox(self.groupBox_window)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.doubleSpinBox_ymax.setFont(font)
        self.doubleSpinBox_ymax.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_ymax.setDecimals(4)
        self.doubleSpinBox_ymax.setMinimum(-100.0)
        self.doubleSpinBox_ymax.setMaximum(100.0)
        self.doubleSpinBox_ymax.setSingleStep(0.001)
        self.doubleSpinBox_ymax.setProperty("value", 0.1)
        self.doubleSpinBox_ymax.setObjectName(_fromUtf8("doubleSpinBox_ymax"))
        self.verticalLayout_y.addWidget(self.doubleSpinBox_ymax)
        self.doubleSpinBox_ymin = QtGui.QDoubleSpinBox(self.groupBox_window)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.doubleSpinBox_ymin.setFont(font)
        self.doubleSpinBox_ymin.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_ymin.setDecimals(4)
        self.doubleSpinBox_ymin.setMinimum(-100.0)
        self.doubleSpinBox_ymin.setMaximum(100.0)
        self.doubleSpinBox_ymin.setSingleStep(0.001)
        self.doubleSpinBox_ymin.setProperty("value", -0.1)
        self.doubleSpinBox_ymin.setObjectName(_fromUtf8("doubleSpinBox_ymin"))
        self.verticalLayout_y.addWidget(self.doubleSpinBox_ymin)
        self.label_ymin = QtGui.QLabel(self.groupBox_window)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ymin.setFont(font)
        self.label_ymin.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_ymin.setObjectName(_fromUtf8("label_ymin"))
        self.verticalLayout_y.addWidget(self.label_ymin)
        self.horizontalLayout.addLayout(self.verticalLayout_y)
        self.gridLayout_bottom.addWidget(self.groupBox_window, 0, 2, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_stimulus = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_stimulus.sizePolicy().hasHeightForWidth())
        self.groupBox_stimulus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_stimulus.setFont(font)
        self.groupBox_stimulus.setFlat(True)
        self.groupBox_stimulus.setObjectName(_fromUtf8("groupBox_stimulus"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_stimulus)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_stim_type = QtGui.QLabel(self.groupBox_stimulus)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_stim_type.setFont(font)
        self.label_stim_type.setObjectName(_fromUtf8("label_stim_type"))
        self.gridLayout_12.addWidget(self.label_stim_type, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_stimulus)
        self.groupBox_threshold = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_threshold.setFont(font)
        self.groupBox_threshold.setFlat(True)
        self.groupBox_threshold.setObjectName(_fromUtf8("groupBox_threshold"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_threshold)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.doubleSpinBox_threshold = QtGui.QDoubleSpinBox(self.groupBox_threshold)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_threshold.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_threshold.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.doubleSpinBox_threshold.setFont(font)
        self.doubleSpinBox_threshold.setDecimals(4)
        self.doubleSpinBox_threshold.setMinimum(-100.0)
        self.doubleSpinBox_threshold.setMaximum(100.0)
        self.doubleSpinBox_threshold.setSingleStep(0.001)
        self.doubleSpinBox_threshold.setObjectName(_fromUtf8("doubleSpinBox_threshold"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_threshold, 0, 0, 1, 1)
        self.pushButton_auto_threshold = QtGui.QPushButton(self.groupBox_threshold)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_auto_threshold.setFont(font)
        self.pushButton_auto_threshold.setObjectName(_fromUtf8("pushButton_auto_threshold"))
        self.gridLayout_4.addWidget(self.pushButton_auto_threshold, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_threshold)
        self.gridLayout_bottom.addLayout(self.verticalLayout, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_bottom, 3, 0, 1, 1)
        self.dockWidget_view = QtGui.QDockWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidget_view.sizePolicy().hasHeightForWidth())
        self.dockWidget_view.setSizePolicy(sizePolicy)
        self.dockWidget_view.setMinimumSize(QtCore.QSize(300, 150))
        self.dockWidget_view.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_view.setObjectName(_fromUtf8("dockWidget_view"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_10 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.view = TraceWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view.sizePolicy().hasHeightForWidth())
        self.view.setSizePolicy(sizePolicy)
        self.view.setObjectName(_fromUtf8("view"))
        self.gridLayout_10.addWidget(self.view, 0, 0, 1, 1)
        self.dockWidget_view.setWidget(self.dockWidgetContents)
        self.gridLayout.addWidget(self.dockWidget_view, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuShow = QtGui.QMenu(self.menuView)
        self.menuShow.setObjectName(_fromUtf8("menuShow"))
        self.menuHide = QtGui.QMenu(self.menuView)
        self.menuHide.setObjectName(_fromUtf8("menuHide"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset = QtGui.QAction(MainWindow)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionView = QtGui.QAction(MainWindow)
        self.actionView.setCheckable(False)
        self.actionView.setChecked(False)
        self.actionView.setObjectName(_fromUtf8("actionView"))
        self.actionAttributes = QtGui.QAction(MainWindow)
        self.actionAttributes.setCheckable(False)
        self.actionAttributes.setChecked(False)
        self.actionAttributes.setAutoRepeat(True)
        self.actionAttributes.setMenuRole(QtGui.QAction.AboutQtRole)
        self.actionAttributes.setObjectName(_fromUtf8("actionAttributes"))
        self.actionLog = QtGui.QAction(MainWindow)
        self.actionLog.setCheckable(False)
        self.actionLog.setChecked(False)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.actionAll_show = QtGui.QAction(MainWindow)
        self.actionAll_show.setObjectName(_fromUtf8("actionAll_show"))
        self.actionAttributes_show = QtGui.QAction(MainWindow)
        self.actionAttributes_show.setObjectName(_fromUtf8("actionAttributes_show"))
        self.actionLog_show = QtGui.QAction(MainWindow)
        self.actionLog_show.setObjectName(_fromUtf8("actionLog_show"))
        self.actionView_show = QtGui.QAction(MainWindow)
        self.actionView_show.setObjectName(_fromUtf8("actionView_show"))
        self.actionAll_hide = QtGui.QAction(MainWindow)
        self.actionAll_hide.setObjectName(_fromUtf8("actionAll_hide"))
        self.actionAttributes_hide = QtGui.QAction(MainWindow)
        self.actionAttributes_hide.setObjectName(_fromUtf8("actionAttributes_hide"))
        self.actionLog_hide = QtGui.QAction(MainWindow)
        self.actionLog_hide.setObjectName(_fromUtf8("actionLog_hide"))
        self.actionView_hide = QtGui.QAction(MainWindow)
        self.actionView_hide.setObjectName(_fromUtf8("actionView_hide"))
        self.menuShow.addAction(self.actionAll_show)
        self.menuShow.addSeparator()
        self.menuShow.addAction(self.actionAttributes_show)
        self.menuShow.addAction(self.actionLog_show)
        self.menuShow.addAction(self.actionView_show)
        self.menuHide.addAction(self.actionAll_hide)
        self.menuHide.addSeparator()
        self.menuHide.addAction(self.actionAttributes_hide)
        self.menuHide.addAction(self.actionLog_hide)
        self.menuHide.addAction(self.actionView_hide)
        self.menuView.addAction(self.actionReset)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuShow.menuAction())
        self.menuView.addAction(self.menuHide.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionReset, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_attributes.show)
        QtCore.QObject.connect(self.actionReset, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_log.show)
        QtCore.QObject.connect(self.actionReset, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_view.show)
        QtCore.QObject.connect(self.actionAttributes_show, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_attributes.show)
        QtCore.QObject.connect(self.actionLog_show, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_log.show)
        QtCore.QObject.connect(self.actionView_show, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_view.show)
        QtCore.QObject.connect(self.actionAttributes_hide, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_attributes.hide)
        QtCore.QObject.connect(self.actionLog_hide, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_log.hide)
        QtCore.QObject.connect(self.actionView_hide, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_view.hide)
        QtCore.QObject.connect(self.actionAll_show, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_attributes.show)
        QtCore.QObject.connect(self.actionAll_show, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_log.show)
        QtCore.QObject.connect(self.actionAll_show, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_view.show)
        QtCore.QObject.connect(self.actionAll_hide, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_attributes.hide)
        QtCore.QObject.connect(self.actionAll_hide, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_log.hide)
        QtCore.QObject.connect(self.actionAll_hide, QtCore.SIGNAL(_fromUtf8("triggered()")), self.dockWidget_view.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Open:", None))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse...", None))
        self.groupBox_review_comments.setTitle(_translate("MainWindow", "Comments ", None))
        self.groupBox_review_test.setTitle(_translate("MainWindow", "Test Number ", None))
        self.groupBox_review_trace.setTitle(_translate("MainWindow", "Trace ", None))
        self.groupBox_review_rep.setTitle(_translate("MainWindow", "Repetition ", None))
        self.groupBox_review_channel.setTitle(_translate("MainWindow", "Channel ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.review), _translate("MainWindow", "Review", None))
        self.groupBox_raster_test.setTitle(_translate("MainWindow", "Test Number ", None))
        self.groupBox_raster_comments.setTitle(_translate("MainWindow", "Comments ", None))
        self.groupBox_raster_trace.setTitle(_translate("MainWindow", "Trace ", None))
        self.groupBox_raster_channel.setTitle(_translate("MainWindow", "Channel ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.raster), _translate("MainWindow", "Raster", None))
        self.groupBox_histogram_test.setTitle(_translate("MainWindow", "Test Number ", None))
        self.groupBox_histogram_comments.setTitle(_translate("MainWindow", "Comments ", None))
        self.groupBox_histogram_trace.setTitle(_translate("MainWindow", "Trace ", None))
        self.groupBox_histogram_channel.setTitle(_translate("MainWindow", "Channel ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.histogram), _translate("MainWindow", "Histogram", None))
        self.groupBox_tc_test.setTitle(_translate("MainWindow", "Test Number ", None))
        self.groupBox_tc_channel.setTitle(_translate("MainWindow", "Channel Number ", None))
        self.groupBox_tc_comments.setTitle(_translate("MainWindow", "Comments ", None))
        self.groupBox_tc_plot.setTitle(_translate("MainWindow", "Plot Type ", None))
        self.radioButton_tc_freq.setText(_translate("MainWindow", "Frequency Response", None))
        self.radioButton_tc_contour.setText(_translate("MainWindow", "Contour Plot", None))
        self.groupBox_tc_error.setTitle(_translate("MainWindow", "Error Bars ", None))
        self.radioButton_tc_stddeviation.setText(_translate("MainWindow", "Standard Deviation", None))
        self.radioButton_tc_stderror.setText(_translate("MainWindow", "Standard Error", None))
        self.radioButton_tc_none.setText(_translate("MainWindow", "None", None))
        self.groupBox_tc_units.setTitle(_translate("MainWindow", "Unit Type ", None))
        self.radioButton_tc_meanspikes.setText(_translate("MainWindow", "Mean Spikes Per Presentation", None))
        self.radioButton_tc_responserate.setText(_translate("MainWindow", "Response Rate (Hz)", None))
        self.groupBox_tc_viewcontrols.setTitle(_translate("MainWindow", "View Controls ", None))
        self.groupBox_tc_view_trace.setTitle(_translate("MainWindow", "Trace ", None))
        self.groupBox_tc_view_channel.setTitle(_translate("MainWindow", "Channel ", None))
        self.groupBox_tc_view_rep.setTitle(_translate("MainWindow", "Repitition ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tuning_curve), _translate("MainWindow", "Tuning Curve", None))
        self.groupBox_abr_min_sep.setTitle(_translate("MainWindow", "Min Separation ", None))
        self.doubleSpinBox_abr_min_sep.setSuffix(_translate("MainWindow", " V", None))
        self.groupBox_abr_test.setTitle(_translate("MainWindow", "Test Number ", None))
        self.groupBox_abr_frequency.setTitle(_translate("MainWindow", "Frequency (hz) ", None))
        self.groupBox_abr_comments.setTitle(_translate("MainWindow", "Comments ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.abr), _translate("MainWindow", "ABR", None))
        self.groupBox_io_test.setTitle(_translate("MainWindow", "Test Number ", None))
        self.groupBox_io_comments.setTitle(_translate("MainWindow", "Comments ", None))
        self.groupBox_io_error.setTitle(_translate("MainWindow", "Error Bars ", None))
        self.radioButton_io_stddeviation.setText(_translate("MainWindow", "Standard Deviation", None))
        self.radioButton_io_stderror.setText(_translate("MainWindow", "Standard Error", None))
        self.radioButton_io_none.setText(_translate("MainWindow", "None", None))
        self.groupBox_io_viewcontrols.setTitle(_translate("MainWindow", "View Controls ", None))
        self.groupBox_io_view_trace.setTitle(_translate("MainWindow", "Trace ", None))
        self.groupBox_io_view_channel.setTitle(_translate("MainWindow", "Channel ", None))
        self.groupBox_io_view_rep.setTitle(_translate("MainWindow", "Repitition ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.io_test), _translate("MainWindow", "I/O Test", None))
        self.groupBox_sr_test.setTitle(_translate("MainWindow", "Test Number ", None))
        self.groupBox_sr_comments.setTitle(_translate("MainWindow", "Comments ", None))
        self.groupBox_sr_viewcontrols.setTitle(_translate("MainWindow", "View Controls ", None))
        self.groupBox_sr_view_trace.setTitle(_translate("MainWindow", "Trace ", None))
        self.groupBox_sr_view_channel.setTitle(_translate("MainWindow", "Channel ", None))
        self.groupBox_sr_view_rep.setTitle(_translate("MainWindow", "Repitition ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.spike_rates), _translate("MainWindow", "Spike Rates", None))
        self.pushButtonGenerate.setText(_translate("MainWindow", "Generate Plot", None))
        self.dockWidget_attributes.setWindowTitle(_translate("MainWindow", "Attributes", None))
        self.dockWidget_log.setWindowTitle(_translate("MainWindow", "Log", None))
        self.groupBox_window.setTitle(_translate("MainWindow", "Use Custom Window ", None))
        self.label_xmax.setText(_translate("MainWindow", "X Max", None))
        self.doubleSpinBox_xmax.setSuffix(_translate("MainWindow", " s", None))
        self.doubleSpinBox_xmin.setSuffix(_translate("MainWindow", " s", None))
        self.label_xmin.setText(_translate("MainWindow", "X Min", None))
        self.label_ymax.setText(_translate("MainWindow", "Y Max", None))
        self.doubleSpinBox_ymax.setSuffix(_translate("MainWindow", " V", None))
        self.doubleSpinBox_ymin.setSuffix(_translate("MainWindow", " V", None))
        self.label_ymin.setText(_translate("MainWindow", "Y Min", None))
        self.groupBox_stimulus.setTitle(_translate("MainWindow", "Stimulus Type ", None))
        self.label_stim_type.setText(_translate("MainWindow", "None", None))
        self.groupBox_threshold.setTitle(_translate("MainWindow", "Threshold ", None))
        self.doubleSpinBox_threshold.setSuffix(_translate("MainWindow", " V", None))
        self.pushButton_auto_threshold.setText(_translate("MainWindow", "Estimate Threshold", None))
        self.dockWidget_view.setWindowTitle(_translate("MainWindow", "View", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuShow.setTitle(_translate("MainWindow", "Show", None))
        self.menuHide.setTitle(_translate("MainWindow", "Hide", None))
        self.actionReset.setText(_translate("MainWindow", "Reset", None))
        self.actionView.setText(_translate("MainWindow", "View", None))
        self.actionAttributes.setText(_translate("MainWindow", "Attributes", None))
        self.actionLog.setText(_translate("MainWindow", "Log", None))
        self.actionAll_show.setText(_translate("MainWindow", "All", None))
        self.actionAttributes_show.setText(_translate("MainWindow", "Attributes", None))
        self.actionLog_show.setText(_translate("MainWindow", "Log", None))
        self.actionView_show.setText(_translate("MainWindow", "View", None))
        self.actionAll_hide.setText(_translate("MainWindow", "All", None))
        self.actionAttributes_hide.setText(_translate("MainWindow", "Attributes", None))
        self.actionLog_hide.setText(_translate("MainWindow", "Log", None))
        self.actionView_hide.setText(_translate("MainWindow", "View", None))

from util.pyqtgraph_widgets import TraceWidget
