# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:/Users/Joel/Documents/AnalysisGui/ui/spike_rates.ui'
#
# Created: Mon Jan 11 15:46:19 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_spike_rates(object):
    def setupUi(self, Form_spike_rates):
        Form_spike_rates.setObjectName(_fromUtf8("Form_spike_rates"))
        Form_spike_rates.setEnabled(True)
        Form_spike_rates.resize(300, 400)
        Form_spike_rates.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("horsey.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_spike_rates.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Form_spike_rates)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_min = QtGui.QLabel(self.centralwidget)
        self.label_min.setObjectName(_fromUtf8("label_min"))
        self.horizontalLayout_2.addWidget(self.label_min)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_max = QtGui.QLabel(self.centralwidget)
        self.label_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_max.setObjectName(_fromUtf8("label_max"))
        self.horizontalLayout_2.addWidget(self.label_max)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 0, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider.setMaximum(100000)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout.addWidget(self.horizontalSlider, 9, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_title = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.horizontalLayout.addWidget(self.label_title)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtGui.QFrame.Panel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 280, 143))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 5, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_spike_rates = QtGui.QPushButton(self.centralwidget)
        self.pushButton_spike_rates.setObjectName(_fromUtf8("pushButton_spike_rates"))
        self.gridLayout_2.addWidget(self.pushButton_spike_rates, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.pushButton_auto_threshold = QtGui.QPushButton(self.centralwidget)
        self.pushButton_auto_threshold.setObjectName(_fromUtf8("pushButton_auto_threshold"))
        self.gridLayout_2.addWidget(self.pushButton_auto_threshold, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 11, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setDecimals(0)
        self.doubleSpinBox.setMaximum(100000.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 10, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_drugs_on = QtGui.QLabel(self.centralwidget)
        self.label_drugs_on.setObjectName(_fromUtf8("label_drugs_on"))
        self.horizontalLayout_5.addWidget(self.label_drugs_on)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.label_drugs_off = QtGui.QLabel(self.centralwidget)
        self.label_drugs_off.setObjectName(_fromUtf8("label_drugs_off"))
        self.horizontalLayout_5.addWidget(self.label_drugs_off)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.timeEdit_on_time = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit_on_time.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_on_time.setObjectName(_fromUtf8("timeEdit_on_time"))
        self.horizontalLayout_4.addWidget(self.timeEdit_on_time)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.timeEdit_off_time = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit_off_time.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_off_time.setObjectName(_fromUtf8("timeEdit_off_time"))
        self.horizontalLayout_4.addWidget(self.timeEdit_off_time)
        self.gridLayout.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        Form_spike_rates.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Form_spike_rates)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Form_spike_rates.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Form_spike_rates)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Form_spike_rates.setStatusBar(self.statusbar)

        self.retranslateUi(Form_spike_rates)
        QtCore.QMetaObject.connectSlotsByName(Form_spike_rates)

    def retranslateUi(self, Form_spike_rates):
        Form_spike_rates.setWindowTitle(_translate("Form_spike_rates", "Spike Rates", None))
        self.label_min.setText(_translate("Form_spike_rates", "Min", None))
        self.label_max.setText(_translate("Form_spike_rates", "Max", None))
        self.label_title.setText(_translate("Form_spike_rates", "Test Name", None))
        self.pushButton_spike_rates.setText(_translate("Form_spike_rates", "Plot", None))
        self.pushButton_auto_threshold.setText(_translate("Form_spike_rates", "Estimate Thresholds", None))
        self.doubleSpinBox.setSuffix(_translate("Form_spike_rates", " ms", None))
        self.label_drugs_on.setText(_translate("Form_spike_rates", "Drugs On Time", None))
        self.label_drugs_off.setText(_translate("Form_spike_rates", "Drugs Off Time", None))
        self.timeEdit_on_time.setDisplayFormat(_translate("Form_spike_rates", "h:mm", None))
        self.timeEdit_off_time.setDisplayFormat(_translate("Form_spike_rates", "h:mm", None))

